# Generated by Django 5.1.6 on 2025-02-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('hero_image_1', models.ImageField(upload_to='home/')),
                ('hero_image_2', models.ImageField(upload_to='home/')),
                ('feature_title', models.CharField(max_length=255)),
                ('feature_description', models.TextField()),
            ],
        ),
    ]
