# Generated by Django 5.1.6 on 2025-02-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_homepagecontent_feature_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='extra_paragraph1',
            field=models.TextField(default='From thrilling game drives to tranquil sunset safaris, Horchen Africa ensures an unforgettable adventure in the wild.', help_text='First extra paragraph.'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='extra_paragraph2',
            field=models.TextField(default='Join us as we explore the vast beauty of Africa, guided by experts who bring every safari to life.', help_text='Second extra paragraph.'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='feature_background',
            field=models.ImageField(help_text='Feature section background image.', upload_to='features/'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_image1',
            field=models.ImageField(help_text='First hero image.', upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_image2',
            field=models.ImageField(help_text='Second hero image.', upload_to='hero/'),
        ),
    ]
