# Generated by Django 5.1.6 on 2025-02-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_homepagecontent_extra_paragraph1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='feature_subtitle',
        ),
    ]
