# Generated by Django 5.1.6 on 2025-02-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_homepagecontent_feature_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Horchen Africa Safaris', max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, default='Discover Africa’s Untamed Beauty', max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='Experience the thrill of the wild with Horchen Africa Safaris.', null=True)),
                ('about_img1', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('about_img2', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('about_img3', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
        ),
    ]
