# Generated by Django 5.1.6 on 2025-03-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='extra_paragraph1',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='extra_paragraph2',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='feature1_description',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='feature1_title',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='feature2_description',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='feature2_title',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='feature3_description',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='feature3_title',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='feature_background',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='feature_title',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='hero_image1',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='hero_image2',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='hero_subtitle',
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_text',
            field=models.TextField(default='Discover breathtaking destinations, immerse yourself in diverse cultures, and create unforgettable memories. Your next adventure starts here!', help_text='Hero section description.'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_title',
            field=models.CharField(default='Explore the World with Us', help_text='Main hero title.', max_length=255),
        ),
    ]
