# Generated by Django 5.1.6 on 2025-03-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_destination_best_time_to_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaripackage',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SafariImage',
        ),
    ]
