# Generated by Django 5.1.6 on 2025-03-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_safaripackage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Gallery Item', 'verbose_name_plural': 'Gallery Items'},
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='caption',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='alt_text',
            field=models.CharField(default='Gallery image', max_length=255),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
