# Generated by Django 5.1.6 on 2025-03-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delete_testimonial_alter_galleryitem_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutSection',
        ),
    ]
