# Generated by Django 5.1.6 on 2025-03-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_delete_aboutsection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itineraryday',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='safaripackage',
            name='best_time_to_visit',
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='max_people',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
